### ISSUE TITLE
Add Update Server in manifest2md.xml

### ISSUE THREAD

**Issue by jbreeding** [elecoest/AE2MD#4]
In order to follow and update the next version of this very nice and usefull Extension, it would be great to insert an manifest2md_update.xml update file and next master_manifest2md.zip file on Git.

`
 <updateservers>
  <server type="extension" priority="1" name="Manifest2md Update Server">https://github.com/elecoest/AE2MD/archive/manifest2md_update.xml</server>
 </updateservers>`

**Comment by elecoest** [comment]
next release
