### ISSUE TITLE
Multilangue component

### ISSUE THREAD

**Issue by micker** [elecoest/AE2MD#6]
it will be great to scan and produce multilangue documentation by scan multiple ini

**Comment by elecoest** [comment]
I'll start with the english language but yes, it's could be a nice idea

**Comment by micker** [comment]
perfect !

**Comment by elecoest** [comment]
some questions : 
- generation for all language installed ? or for one chosen ?
- language on the extension item ? so for a documenattion gesration in EN et FR, you will have 2 entries in the extensions page...
- for the generation, for the moment I've /documentation/Category_alias/modules/..., whith the langugage, somme possibilities : /documentation/en-GB/Category_alias/modules/..., /documentation/Category_alias/en-GB/modules/..., /documentation/Category_alias/modules/en-GB... Wich one ?

Manu

**Comment by micker** [comment]
I think all file language peer component module plugins will be good
Maybe After an option to select language but i think all component creator want all language lol

Le 6 mai 2017 à 09:15, à 09:15, Emmanuel Lecoester <notifications@github.com> a écrit:

**Comment by micker** [comment]
But on of question is how to integreate this on marcknote ?

**Comment by elecoest** [comment]
No problem to integrate them in marknotes... the only obligation : a sub
directory on /documentation :)

Manu

2017-05-06 9:23 GMT+02:00 Berges Yannick <notifications@github.com>:

**Comment by micker** [comment]
Very good .... 

Le 6 mai 2017 à 09:47, à 09:47, Emmanuel Lecoester <notifications@github.com> a écrit:

**Comment by elecoest** [comment]
but the question is still open : HOW ?


2017-05-06 9:53 GMT+02:00 Berges Yannick <notifications@github.com>:

**Comment by micker** [comment]
Désoler je comprend pas en plus je suis limite en eng lol

Le 6 mai 2017 à 10:04, à 10:04, Emmanuel Lecoester <notifications@github.com> a écrit:

**Comment by elecoest** [comment]
le code lange je l'affiche ou dans l'arboresecence ?

je dirais au niveau le plus bas donc en tout premier :
/documentation/en-GB/Ma_catégorie
/documentation/fr-FR/Ma_catégorie

2017-05-06 10:11 GMT+02:00 Berges Yannick <notifications@github.com>:

**Comment by micker** [comment]
Oui parfait

Le 6 mai 2017 à 10:27, à 10:27, Emmanuel Lecoester <notifications@github.com> a écrit:

**Comment by elecoest** [comment]
done
